"""Add areation datetime column

Revision ID: 0c0039cddbfc
Revises: 77adf0896f72
Create Date: 2023-08-28 22:09:28.164582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0039cddbfc'
down_revision: Union[str, None] = '77adf0896f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrie', sa.Column('creation_datetime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrie', 'creation_datetime')
    # ### end Alembic commands ###
