"""Added default for creation datetime column

Revision ID: 4ba832d9c71e
Revises: 0c0039cddbfc
Create Date: 2023-08-28 22:26:20.211797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba832d9c71e'
down_revision: Union[str, None] = '0c0039cddbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
